export const GAME_ACTIONS = {
    CREATE_GAME_REQUEST: "CREATE_GAME_REQUEST",
    CREATE_GAME_SUCCESS: "CREATE_GAME_SUCCESS",
    CREATE_GAME_FAILURE: "CREATE_GAME_FAILURE",
    UPDATE_GAME_REQUEST: "UPDATE_GAME_REQUEST",
    UPDATE_GAME_SUCCESS: "UPDATE_GAME_SUCCESS",
    UPDATE_GAME_FAILURE: "UPDATE_GAME_FAILURE",
    CONFIRM_GAME_FAILURE: "CONFIRM_GAME_FAILURE",
    CONFIRM_GAME_REQUEST: "CONFIRM_GAME_REQUEST",
    CONFIRM_GAME_SUCCESS: "CONFIRM_GAME_SUCCESS",
};
