@MatrixScrabble.Server_HostAddress = http://localhost:5032

GET {{MatrixScrabble.Server_HostAddress}}/weatherforecast/
Accept: application/json

POST {{MatrixScrabble.Server_HostAddress}}/word/
Accept: application/json
###
